version: '3'
services:
  datajoint:
    build: .
    container_name: ibl_datajoint_test
    env_file: .env_test
    volumes:
      - ./notebooks:/notebooks
      - ./images:/images
      - .:/src/IBL-pipeline
      - ./data:/data
      - ./root/.one_params:/root/.one_params
    ports:
      - "8900:8888"
