version: '3'
services:
  datajoint_dbtest:
    build: .
    container_name: ibl_datajoint_dbtest
    env_file: .env_dbtest
    volumes:
      - ./notebooks:/notebooks
      - ./images:/images
      - .:/src/IBL-pipeline
      - ./data:/data
      - ./root/.one_params:/root/.one_params
    ports:
      - "8400:8888"
